version: '2'
services:
  nexus3:
    image: sonatype/nexus3:3.7.1
    restart: always
    container_name: nexus3
    ports:
      - 8081:8081
    volumes:
      - /data/compose/nexus-data:/nexus-data
networks:
  default:
    external:
      name: service

