influxdb:
  image: influxdb:1.4
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "25826:25826/udp"
  volumes:
    - /var/lib/influxdb
    - ./influxdb.conf:/etc/influxdb/influxdb.conf
    - ./types.db:/usr/share/collectd/types.db:ro
